# Generated by Django 3.1.6 on 2021-02-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money_app', '0002_auto_20210218_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='month',
            field=models.ManyToManyField(blank=True, related_name='month', to='Money_app.Month', verbose_name='month'),
        ),
    ]
