# Generated by Django 3.1.6 on 2021-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money_app', '0003_auto_20210218_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
